Update husky pre-commit hooked for tsed project

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,64 +2,64 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 x=1
-if git diff --cached --quiet -- "api/*.ts"; then
-  echo "%===================================%"
-  echo "= $x No changes in .ts API (Skipping)"
-  echo "%===================================%"
+if git diff --cached --quiet -- "server/*.ts"; then
+  echo "%=============================================================================================%"
+  echo "= $x No .ts changes in Server (Skipping)"
+  echo "%=============================================================================================%"
 else 
-  echo "%===================================%"
-  echo "= $x Found changes in API."
-  echo "%===================================%"
+  echo "%=============================================================================================%"
+  echo "= $x Found changes in Server."
+  echo "%=============================================================================================%"
   {
-    echo "%===================================%"
-    echo "= $x:A Linting API..."
-    echo "%===================================%"
-    npm run lint:api
+    echo "%=============================================================================================%"
+    echo "= $x:A Linting Server..."
+    echo "%=============================================================================================%"
+    npm run lint:server
   } || {
     x=x+0.5
-    echo "%===================================%"
-    echo "= X You have eslint errors in API. Please fix them before committing." 1>&2
-    echo "%===================================%"
+    echo "%=============================================================================================%"
+    echo "= X You have eslint errors in Server. Please fix them before committing." 1>&2
+    echo "%=============================================================================================%"
     false
   }
 
-  echo "%===================================%"
-  echo "= $x:B Formatting API..."
-  echo "%===================================%"
-  npm run format:api
+  echo "%=============================================================================================%"
+  echo "= $x:B Formatting Server..."
+  echo "%=============================================================================================%"
+  npm run format:server
 
   x=$((x+1))
 fi
 
 
 if git diff --cached --name-only --quiet -- "client/*.ts"; then
-  echo "%===================================%"
-  echo "= $x No changes in .ts Client (Skipping)"
-  echo "%===================================%"
+  echo "%=============================================================================================%"
+  echo "= $x No .ts changes in Client (Skipping)"
+  echo "%=============================================================================================%"
 else
-  echo "%===================================%"
+  echo "%=============================================================================================%"
   echo "= $x Found changes in Client."
-  echo "%===================================%"
+  echo "%=============================================================================================%"
   {
-    echo "%===================================%"
+    echo "%=============================================================================================%"
     echo "= $x:A Linting Client..."
-    echo "%===================================%"
+    echo "%=============================================================================================%"
     npm run lint:client
   } || {
-    echo "%===================================%"
+    echo "%=============================================================================================%"
     echo "= X You have eslint errors in Client. Please fix them before committing." 1>&2
-    echo "%===================================%"
+    echo "%=============================================================================================%"
     false
   }
 
-  echo "%===================================%"
+  echo "%=============================================================================================%"
   echo "= $x:B Formatting Client..."
-  echo "%===================================%"
+  echo "%=============================================================================================%"
   npm run format:client
 
-  echo "%===================================%"
+  echo "%=============================================================================================%"
   echo "= $x:C Removing environment variables..."
-  echo "%===================================%"
+  echo "%=============================================================================================%"
   npm run clean:env
 
   if git diff --name-only --quiet ./client/src/environments/*; then
